alice_2_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  # left leg ---------------------------------------
  l_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_knee_pitch_position:
    type: effort_controllers/JointPositionController
    joint: leg_knee_l
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_ankle_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_ankle_pitch
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_ankle_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_ankle_roll
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # right leg ---------------------------------------
  r_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_knee_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_knee_pitch
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_ankle_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_ankle_pitch
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_ankle_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_ankle_roll
    pid: {p: 7500.0, i: 0.1, d: 100.0}



